<h1>Alexis Soto-Colorado</h1>
<h2>Please download the Seaborn library because I used during my code</h2>

In [18]:
import geopandas as gp
import pandas as pd
import os
import json
import sys
import urllib2
import pylab as pl
import statsmodels.api as sm
import statsmodels.formula.api as smf
import seaborn as sns

%pylab inline

Populating the interactive namespace from numpy and matplotlib

In [19]:
#Adding January Data of City Bike
jan_bike =bike=pd.read_csv('http://cosmo.nyu.edu/~fb55/UI_CUSP_2015/data/201501-citibike-tripdata.csv')
jan_bike.head().transpose()

,0,1,2,3,4
tripduration,1346,363,346,182,969
starttime,1/1/2015 0:01,1/1/2015 0:02,1/1/2015 0:04,1/1/2015 0:04,1/1/2015 0:05
stoptime,1/1/2015 0:24,1/1/2015 0:08,1/1/2015 0:10,1/1/2015 0:07,1/1/2015 0:21
start station id,455,434,491,384,474
start station name,1 Ave & E 44 St,9 Ave & W 18 St,E 24 St & Park Ave S,Fulton St & Waverly Ave,5 Ave & E 29 St
start station latitude,40.75002,40.74317,40.74096,40.68318,40.74517
start station longitude,-73.96905,-74.00366,-73.98602,-73.96596,-73.98683
end station id,265,482,505,399,432
end station name,Stanton St & Chrystie St,W 15 St & 7 Ave,6 Ave & W 33 St,Lafayette Ave & St James Pl,E 7 St & Avenue A
end station latitude,40.72229,40.73936,40.74901,40.68852,40.72622
end station longitude,-73.99148,-73.99932,-73.98848,-73.96476,-73.9838
bikeid,18660,16085,20845,19610,20197
usertype,Subscriber,Subscriber,Subscriber,Subscriber,Subscriber
birth year,1960,1963,1974,1969,1977
gender,2,1,1,1,1

In [20]:
#Learn in the Friday Seminar
jan_bike.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
tripduration,285552,654.325583,900.775928,60.000000,334.000000,504.000000,772.000000,43023.000000
start station id,285552,443.535006,332.580265,72.000000,308.000000,417.000000,492.000000,3002.000000
start station latitude,285552,40.735804,0.018773,40.680342,40.723627,40.738274,40.750450,40.771522
start station longitude,285552,-73.990177,0.011681,-74.017134,-73.998102,-73.990093,-73.981854,-73.950048
end station id,285552,440.337557,326.010259,72.000000,307.000000,417.000000,492.000000,3002.000000
end station latitude,285552,40.735607,0.018718,40.680342,40.723180,40.737815,40.750200,40.771522
end station longitude,285552,-73.990398,0.011742,-74.017134,-73.998522,-73.990617,-73.981854,-73.950048
bikeid,285552,18147.291481,2065.313794,14529.000000,16355.000000,18148.000000,19903.000000,21690.000000
birth year,279924,1974.951419,11.574637,1899.000000,1967.000000,1977.000000,1984.000000,1999.000000
gender,285552,1.162485,0.419490,0.000000,1.000000,1.000000,1.000000,2.000000

In [21]:
#Adding February Data of City Bikes
feb_bike = bike=pd.read_csv('http://cosmo.nyu.edu/~fb55/UI_CUSP_2015/data/201502-citibike-tripdata.csv')
feb_bike.head().transpose()

,0,1,2,3,4
tripduration,801,379,2474,818,544
starttime,2/1/2015 0:00,2/1/2015 0:00,2/1/2015 0:01,2/1/2015 0:01,2/1/2015 0:01
stoptime,2/1/2015 0:14,2/1/2015 0:07,2/1/2015 0:42,2/1/2015 0:15,2/1/2015 0:10
start station id,521,497,281,2004,323
start station name,8 Ave & W 31 St,E 17 St & Broadway,Grand Army Plaza & Central Park S,6 Ave & Broome St,Lawrence St & Willoughby St
start station latitude,40.75045,40.73705,40.7644,40.7244,40.69236
start station longitude,-73.99481,-73.99009,-73.97371,-74.0047,-73.98632
end station id,423,504,127,505,83
end station name,W 54 St & 9 Ave,1 Ave & E 15 St,Barrow St & Hudson St,6 Ave & W 33 St,Atlantic Ave & Fort Greene Pl
end station latitude,40.76585,40.73222,40.73172,40.74901,40.68383
end station longitude,-73.98691,-73.98166,-74.00674,-73.98848,-73.97632
bikeid,17131,21289,18903,21044,19868
usertype,Subscriber,Subscriber,Subscriber,Subscriber,Subscriber
birth year,1978,1993,1969,1985,1957
gender,2,1,2,2,1

In [22]:
#Joining the Two Sets for Data Analysis Simplification
dataBike = pd.concat([jan_bike,feb_bike])
print len(dataBike)
dataBike.head().transpose()

482482

,0,1,2,3,4
tripduration,1346,363,346,182,969
starttime,1/1/2015 0:01,1/1/2015 0:02,1/1/2015 0:04,1/1/2015 0:04,1/1/2015 0:05
stoptime,1/1/2015 0:24,1/1/2015 0:08,1/1/2015 0:10,1/1/2015 0:07,1/1/2015 0:21
start station id,455,434,491,384,474
start station name,1 Ave & E 44 St,9 Ave & W 18 St,E 24 St & Park Ave S,Fulton St & Waverly Ave,5 Ave & E 29 St
start station latitude,40.75002,40.74317,40.74096,40.68318,40.74517
start station longitude,-73.96905,-74.00366,-73.98602,-73.96596,-73.98683
end station id,265,482,505,399,432
end station name,Stanton St & Chrystie St,W 15 St & 7 Ave,6 Ave & W 33 St,Lafayette Ave & St James Pl,E 7 St & Avenue A
end station latitude,40.72229,40.73936,40.74901,40.68852,40.72622
end station longitude,-73.99148,-73.99932,-73.98848,-73.96476,-73.9838
bikeid,18660,16085,20845,19610,20197
usertype,Subscriber,Subscriber,Subscriber,Subscriber,Subscriber
birth year,1960,1963,1974,1969,1977
gender,2,1,1,1,1

In [23]:
#Open the JSON Zip Code Data and Intengrate to the Python Dataframe
webUrl = urllib2.urlopen('http://cosmo.nyu.edu/~fb55/UI_CUSP_2015/data/stationzips.json')
datazipcode = webUrl.read()
jsonData = json.loads(datazipcode)
print jsonData

{u'344': 11216, u'345': 10011, u'346': 10014, u'347': 10014, u'340': 10002, u'341': 10002, u'342': 10002, u'343': 11251, u'348': 10012, u'349': 10002, u'478': 10036, u'298': 11217, u'296': 10002, u'297': 10003, u'294': 10003, u'295': 10002, u'293': 10003, u'290': 10022, u'291': 10002, u'195': 10005, u'270': 11205, u'3141': 10065, u'3142': 10065, u'274': 11217, u'275': 11238, u'276': 10013, u'3147': 10028, u'3148': 10028, u'279': 10038, u'524': 10036, u'525': 10001, u'526': 10016, u'527': 10016, u'520': 10019, u'521': 10001, u'522': 10022, u'523': 10018, u'528': 10016, u'529': 10036, u'449': 10019, u'448': 10018, u'443': 11211, u'442': 10001, u'441': 10022, u'440': 10017, u'447': 10019, u'446': 10001, u'445': 10009, u'444': 10010, u'3092': 11211, u'3093': 11211, u'3090': 11211, u'3091': 11211, u'3097': 11222, u'438': 10003, u'439': 10003, u'436': 11216, u'437': 11216, u'3098': 11222, u'435': 10011, u'432': 10009, u'433': 10009, u'430': 11201, u'431': 11201, u'339': 10009, u'335': 10003, u'334': 10011, u'337': 10005, u'336': 10012, u'331': 10002, u'330': 10007, u'332': 10002, u'238': 10014, u'239': 11201, u'3063': 11206, u'3062': 11206, u'3061': 11206, u'3060': 11206, u'3067': 11206, u'3066': 11206, u'3065': 11206, u'3064': 11206, u'236': 10003, u'237': 10003, u'3069': 11206, u'232': 11201, u'233': 11201, u'3068': 11206, u'146': 10013, u'147': 10007, u'144': 11201, u'143': 11201, u'3119': 11101, u'3118': 11222, u'3117': 11222, u'3115': 11222, u'3114': 11222, u'3113': 11222, u'3112': 11222, u'3111': 11222, u'3110': 11222, u'137': 10022, u'499': 10023, u'494': 10001, u'495': 10036, u'496': 10003, u'497': 10003, u'490': 10001, u'491': 10010, u'492': 10001, u'493': 10036, u'407': 11201, u'406': 11201, u'405': 10014, u'404': 10014, u'403': 10003, u'402': 10010, u'401': 10002, u'400': 10002, u'2017': 10017, u'2010': 10013, u'409': 11205, u'2012': 10016, u'379': 10001, u'373': 11205, u'372': 11205, u'375': 10012, u'377': 10013, u'376': 10038, u'393': 10009, u'392': 11201, u'391': 11201, u'390': 11201, u'397': 11238, u'396': 11238, u'395': 11217, u'394': 10009, u'82': 10038, u'83': 11217, u'399': 11205, u'398': 11201, u'245': 11201, u'244': 11205, u'247': 10014, u'3150': 10028, u'241': 11201, u'3156': 10021, u'243': 11217, u'242': 11205, u'3159': 10023, u'3158': 10023, u'249': 10013, u'248': 10013, u'224': 10038, u'3016': 10021, u'3014': 11211, u'519': 10017, u'518': 10016, u'511': 10009, u'510': 10019, u'513': 10019, u'512': 10001, u'515': 10036, u'514': 10019, u'517': 10017, u'516': 10017, u'458': 10001, u'459': 10011, u'450': 10019, u'453': 10011, u'454': 10022, u'455': 10017, u'456': 10022, u'457': 10019, u'174': 10016, u'173': 10019, u'3088': 11211, u'3085': 11211, u'3084': 11211, u'3087': 11211, u'3086': 11211, u'3081': 11211, u'3080': 11211, u'3083': 11211, u'3082': 11211, u'3140': 10075, u'271': 11217, u'2021': 10036, u'2022': 10022, u'2023': 10022, u'3144': 10028, u'3145': 10028, u'3146': 10028, u'278': 11201, u'3149': 10028, u'3232': 11201, u'3230': 10001, u'3231': 10065, u'322': 11201, u'323': 11201, u'320': 10013, u'321': 11201, u'326': 10003, u'327': 10282, u'324': 11201, u'325': 10003, u'328': 10013, u'329': 10013, u'72': 10019, u'3058': 11221, u'3059': 11206, u'3056': 11216, u'3057': 11221, u'3054': 11221, u'3055': 11216, u'3052': 11221, u'3053': 11216, u'3050': 11221, u'3070': 11206, u'3071': 11206, u'266': 10009, u'229': 10012, u'228': 10017, u'3079': 11206, u'3128': 11101, u'3129': 11101, u'3123': 11101, u'3120': 11101, u'3121': 11101, u'3126': 11101, u'3127': 11101, u'3124': 11101, u'3125': 11101, u'540': 10016, u'546': 10016, u'545': 10010, u'120': 11238, u'127': 10014, u'128': 10014, u'414': 11201, u'415': 10005, u'416': 11205, u'417': 10007, u'410': 10002, u'411': 10009, u'412': 10002, u'498': 10001, u'418': 11201, u'419': 11205, u'319': 10007, u'318': 10017, u'313': 11205, u'312': 10002, u'311': 10002, u'310': 11201, u'317': 10009, u'316': 10038, u'315': nan, u'314': 11201, u'368': 10014, u'369': 10011, u'366': 11205, u'367': 10022, u'364': 11205, u'365': 11238, u'362': 10018, u'363': 10280, u'360': 10005, u'361': 10002, u'380': 10014, u'382': 10003, u'383': 10011, u'384': 11238, u'385': 10022, u'386': 10007, u'387': 10007, u'388': 10001, u'389': 11211, u'258': 11205, u'259': 10004, u'3002': 10281, u'252': 10011, u'253': 10011, u'250': 10012, u'251': 10012, u'257': 10013, u'254': 10011, u'255': 11220, u'508': 10036, u'509': 10011, u'507': 10010, u'504': 10009, u'505': 10001, u'502': 10002, u'503': 10003, u'500': 10019, u'501': 10016, u'469': 10019, u'468': 10019, u'465': 10036, u'464': 10022, u'467': 11217, u'466': 10010, u'461': 10003, u'460': 11211, u'463': 10011, u'462': 10011, u'168': 10011, u'164': 10017, u'167': 10016, u'160': 10016, u'161': 10012, u'408': 10002, u'3180': 11201, u'3181': 10004, u'3182': 10004, u'3094': 11211, u'3095': 11222, u'434': 10011, u'263': 10013, u'262': 11201, u'3224': 10014, u'3226': 10024, u'3221': 11101, u'261': 11201, u'3223': 10022, u'3222': 11217, u'357': 10003, u'356': 10002, u'355': 10013, u'354': 11205, u'353': 11217, u'352': 10019, u'351': 10005, u'350': 10002, u'359': 10017, u'358': 10014, u'216': 11201, u'217': 11201, u'212': 10011, u'265': 10002, u'264': 10005, u'218': 11201, u'3049': 11238, u'3048': 11216, u'3041': 11216, u'3043': 11233, u'3042': 11233, u'3044': 11216, u'3047': 11216, u'3046': 11216, u'289': 11238, u'281': 10019, u'280': 10003, u'282': 11211, u'285': 10003, u'284': 10014, u'3135': 10021, u'3134': 10065, u'3137': 83, u'260': 10004, u'267': 10018, u'3130': 11101, u'3133': 10065, u'3132': 10022, u'268': 10013, u'3139': 10021, u'537': 10010, u'536': 10016, u'534': 10004, u'533': 10018, u'532': 11211, u'531': 10002, u'530': 10019, u'539': 11211, u'538': 10017, u'3169': 10024, u'3166': 10023, u'116': 10011, u'3167': 10023, u'119': 11205, u'3164': 10023, u'3165': 83, u'3163': 83, u'428': 10003, u'3160': 83, u'421': 11205, u'420': 11238, u'423': 10019, u'422': 10019, u'427': 10004, u'426': 10013, u'308': 10038, u'309': 10007, u'300': 10003, u'301': 10009, u'302': 10009, u'303': 10012, u'304': 10004, u'305': 10022, u'306': 10038, u'307': 10002, u'79': 10013, u'3179': 11206, u'3178': 10023, u'3072': 11206, u'3073': 11211, u'3074': 11206, u'3075': 11211, u'3076': 11206, u'3077': 11211, u'3170': 10024, u'225': 10014, u'3172': 10023, u'223': 10011, u'3177': 10024, u'3176': 10023, u'470': 10011, u'3136': 83, u'151': 10012, u'150': 10009, u'153': 10016, u'152': 10007, u'157': 11201, u'472': 10016, u'3108': 11222, u'3109': 11222, u'473': 10002, u'3104': 11211, u'3105': 11222, u'3106': 11222, u'3107': 11222, u'3101': 11222, u'3102': 11222, u'3103': 11211, u'471': 11211, u'3175': 10023, u'476': 10016, u'474': 10016, u'475': 10003, u'489': 10001, u'488': 10018, u'487': 10009, u'486': 10001, u'485': 10018, u'484': 10036, u'483': 10003, u'482': 10011, u'481': 11211, u'480': 10019, u'479': 10036, u'2002': 11211, u'2003': 10009, u'2000': 11201, u'2001': 11251, u'2006': 83, u'477': 10018, u'2004': 10013, u'2005': 11251, u'2008': 10280, u'2009': 10038}

In [24]:
#Get GIS Data into Python for Analysis 
gis = gp.GeoDataFrame.from_file("MNMapPLUTO.shp")
print gis.columns

Index([    u'APPBBL',    u'APPDate',    u'Address', u'AllZoning1',
       u'AllZoning2', u'AreaSource', u'AssessLand',  u'AssessTot',
              u'BBL',   u'BldgArea',  u'BldgClass',  u'BldgDepth',
        u'BldgFront',      u'Block',   u'BoroCode',    u'Borough',
         u'BsmtCode',  u'BuiltCode',   u'BuiltFAR',     u'CB2010',
               u'CD',     u'CT2010',    u'ComArea',    u'CommFAR',
          u'CondoNo',    u'Council',  u'EDesigNum',  u'Easements',
       u'ExemptLand',  u'ExemptTot',        u'Ext',   u'FacilFAR',
       u'FactryArea',   u'FireComp', u'GarageArea', u'HealthArea',
         u'HistDist', u'IrrLotCode',    u'LandUse',   u'Landmark',
              u'Lot',    u'LotArea',   u'LotDepth',   u'LotFront',
          u'LotType',  u'LtdHeight', u'MAPPLUTO_F',   u'NumBldgs',
        u'NumFloors', u'OfficeArea',  u'OtherArea',   u'Overlay1',
         u'Overlay2',  u'OwnerName',  u'OwnerType', u'PLUTOMapID',
       u'PolicePrct',   u'ProxCode',    u'ResArea',   u'ResidFAR',
       u'RetailArea', u'SHAPE_Area', u'SHAPE_Leng',    u'SPDist1',
          u'SPDist2',    u'Sanborn', u'SchoolDist',  u'SplitZone',
        u'StrgeArea',     u'TaxMap',  u'Tract2010',   u'UnitsRes',
       u'UnitsTotal',    u'Version',     u'XCoord',     u'YCoord',
       u'YearAlter1', u'YearAlter2',  u'YearBuilt',     u'ZMCode',
          u'ZipCode',  u'ZoneDist1',  u'ZoneDist2',  u'ZoneDist3',
        u'ZoneDist4',    u'ZoneMap',   u'geometry'],
      dtype='object')

In [25]:
#ADDING ZipCode to dataBike Dataframe Using the Start Station ID as the Link
dataBike['ZipCode'] = [jsonData[str(istr)] for istr in dataBike['start station id']]

In [26]:
#Grouping and Counting Users by ZipCode
UserZipCode = (dataBike['start station id'].groupby(dataBike['ZipCode']).count())
print UserZipCode

ZipCode
83         778
10001    41728
10002    29223
10003    54234
10004     3460
10005     5960
10007    10766
10009    27704
10010    19750
10011    41566
10012    18914
10013    18638
10014    25395
10016    35352
10017    23770
10018    18652
10019    28121
10022    12828
10023     2296
10036    19993
10038     6966
10280     2061
10281     1747
10282     2412
11201    13896
11205     5945
11211     3002
11216      615
11217     3585
11238     2074
11251      345
Name: start station id, dtype: int64

In [1]:
#Counting  Residential Unit per ZipCode and Grouping it by ZipCode
#ResidentZipCode = (bsize['UnitsRes'].groupby(bsize['ZipCode']).sum())
#print ResidentZipCode

In [ ]:
#Link Together using Concatenate from Panda Everything Residential Units by ZipCode with their Correspondence Station ID
DataZipCode = pd.concat([UserZipCode,ResidentZipCode], axis=1)
print DataZipCode

In [ ]:
#Following Data Cleaning Standard by Eliminiting NaN or Zeros Values
ShowData = DataZipCode[~((np.isnan(DataZipCode['UnitsRes'])) | (np.isnan(DataZipCode['start station id']))) & (DataZipCode['UnitsRes']<40000)]
print ShowData

In [ ]:
#Create a Scatter Plot 
X = ShowData['UnitsRes']
Y = ShowData['start station id']
plt.scatter(X,Y)
plt.ylabel('Rides per ZipCode')
plt.xlabel('Residential Units per ZipCode')
plt.title('Numbers of Residential Units Versus Zip Code Ride')

In [ ]:
# Doing Some Stat 'Regression with a fix" 
model1 = smf.ols(formula = "y  ~ X-1", 
        data={'X':ShowData['UnitsRes'],'y': ShowData['start station id']},missing='drop')
fit1 = model1.fit()
Likelihood_1 = fit1.llf
Xord = linspace(min(X),max(X),50)
Yord1 = fit1

#Problem running the code here "not defined lmy". I used instead seaborn below for my graph needs.
#plt.plot(X,lmy,'-r')

plt.plot(X,Y,'o',ms=4)
plt.ylabel('Rides in the ZipCode')
plt.xlabel('Residential Units in ZipCode')
plt.title('Scatter Plot of the Data with Regression')
fit1.summary()

In [ ]:
#Using Seaborn to show graph that doesn't show in the code above
# Example Code sns.regplot(x="total_bill", y="tip", data=tips);
sns.regplot(x="UnitsRes", y='start station id', data=ShowData)

<h2>What it means?</h2>
For sure, we have a positive correlation between number Residential Unit by Zip Codes because the R 0.869 is closed.  to 1.

In [ ]:
#Adding some normalization to the data
curvemodel = smf.ols(formula = "Y  ~ X+I(X**2)", 
        data={'X':ShowData['UnitsRes'],'Y': ShowData['start station id']},missing='drop')
fit2 = curvemodel.fit()
Likelihood_2 = fit2.llf
lr = -2.0*(Likelihood_1 - Likelihood_2)
Yord = fit2.params[2] * Xord **2 + fit2.params[1] * Xord + fit2.params[0]

#Same issue as above
#plt.plot(X,lmy,'r-')

plt.plot(Xord,Yord,'b-')
plt.plot(X,Y,'o',ms=4)
plt.ylabel('Rides per ZipCode')
plt.xlabel('Residential Units per ZipCode')
plt.title('Scatter plot of the data')
fit2.summary()

<h2>What it means?</h2>
I am not sure the correlation between number Residential Unit by Zip Codes because the R 0.631 is not closed to 1. In this case, I will make the assumption that the correlaction is not that strong as was showed in the previos stat results. Even thought isn't strong as above, it doesn't means that there isn't correlaction.

<h2>Discuss</h2>
<ul>
<li><strong>If the test could be improved: the number of residential units may be a good predictor under specific circumstances (restricting your dataset by any variable, eg only certain times, days, areas, what do you think?)</strong></li>  In order to improve the test, two things need to happend:
<ol>
<li>Increase the size of the sample by adding more months and whole years</li>
<li>Geography Correlaction need to be study. Not all the areas of the City can be consider equal. As example density and traffic can be big factor in deciding if people use bike or not.

</ol>

<li><strong>If you have time test these other hypothesis (for extra credit). Try and imagine what variable could be a better predictor (and if you have time test other vatiables also for extra credit).</strong></li> I will go to the point above the most important variable that need to be tested will be "geography" or "spatial analysis" because it can give you knowledge about issue that may affect ridership like demographic for example. Not everyone have the same positive attitude above riding the bike. For example white tend to be more positive to bicycles than blacks. The attitudes of ridership among racial and ethnic groups should be study.

In [ ]:
%whos